require:
  - rubocop-rspec
Metrics:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/SymbolArray:
  MinSize: 100

Style/WordArray:
  MinSize: 100

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Naming/MethodParameterName:
    MinNameLength: 1

RSpec:
  Exclude:
    - "spec/factories/*"
RSpec/AnyInstance:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false